[package]
name = "world-id-marbles"
version = "0.1.0"
edition = "2021"
description = "Marble generator for World ID."
license = "MIT"
repository = "https://github.com/m1guelpf/world-id-marbles"
readme = "README.md"
keywords = ["marbles", "world-id"]
categories = ["library"]

[dependencies]
indoc = "2.0.1"
ruint = "1.8.0"
anyhow = "1.0.70"
resvg = { git = "https://github.com/zimond/resvg", rev = "0556558", default-features = false, features = ["png", "filter"] }
